### ISSUE TITLE
MyBatis3RenderingStrategy is incompatible with myBatis3 ?

### ISSUE THREAD

**Issue by tnicolas29200** [mybatis/mybatis-dynamic-sql#1]
Hello,

Thank you for this great library.

I test it for some days but i encounter a problem : when i use the MyBatis3RenderingStrategy like the samples, i can't use easily like the myBatis3 functionnal call : 

With MyBatis dynamic sql, i can write a query like :
`select id from table where id = #{id}`

with a function like :
`public Dto selectById(@Param(value = "id") Integer id);`

myBatis automatically map the id parameter, that's great !

But with the new DynamicSql MyBatis3RenderingStrategy, the same query is formatted like this :
`select id from table where id = #{parameters.p1,jdbcType=INTEGER}`

and myBatis is unable to map the id parameter.

I can use a Parameter bean containing the sql query and the id parameter, but i prefer to use parameters on function call rather than using a new bean for each call.

So i have wrote my own Renderer like this :
`public class SimpleMyBatis3RenderingStrategy extends RenderingStrategy {
	@Override
	public String getFormattedJdbcPlaceholder(BindableColumn<?> column, String prefix, String parameterName) {
		return "#{"+ ((SqlColumn) column).name() + "}";
	}
}`

It's not very pretty, i know, but it works.

Have you planned to make this kind of Renderer in future ?
Or maybe there is another method to use for generating a compatible query with the functionnal calling ?

**Comment by jeffgbutler** [comment]
I'm not sure I understand your usage.  If you are writing your own SQL, then this library isn't really going to help you.  The library is designed to create a single object that holds both the SQL statement and the parameters - and the library generates the SQL for you.

That's why the parameters are formatted as they are - they refer back to the Map in the generated object.

If I'm missing something, please feel free to attach a more complete code example.

**Comment by tnicolas29200** [comment]
Thank you for your response.

I'a using your new library for replacing the old SQLGenerator of myBatis : i have done my own SQLGenerator inspiring of yours with the same approch of your new library, but very less complete.

I have very excited when i see this new library because it respond at my goal, but i have thinking that i can use it in replacement of the old SQL Generator : you use it by a simple function call with some parameters to execute your query without a bean containing all the parameters of the query.
Personnaly, i prefer to call a function with many parameters rather than creating a new bean with some parameters for querying the database : it's a little bit more efficient for the garbage collector and it permit to maintain an interface with some queries rather than multiple beans.

The missing thing is just a RenderingStrategy which is compatible with the functionnal calling of MyBatis.I have wrote one myself, but maybe you can integrate it on the library in a more standard way. I will create a pull request in few hours to show you what i mean.

**Comment by jeffgbutler** [comment]
Ok - I think I understand.  You want to use the library to generate SQL but still want to code your own more traditional MyBatis methods.

The library is going to create the new object regardless of whether you use it or not, so I don't think there's any impact on garbage collection.

I can understand that you want to use MyBatis in a more traditional way and your rendering strategy would make that possible.  My concern is that using a rendering strategy like this places a large burden on the user - the user needs to make sure that the parameters are named properly based on what the library renders.  That's not too hard for simple things like your example, but it can quickly get very complex if you use "in" queries, or do joins or unions.

One of my goals in creating the library was to make it easy to extend.  I think you've shown that you can write a new rendering strategy like this and use the library in a way I hadn't anticipated - and that is awesome.  But I don't think it would be appropriate to add this to the base code of the library itself because it's too fragile for a general user.

If I'm still not understanding, would you attach a full example of what you're proposing?

**Comment by tnicolas29200** [comment]
Hello,

Yes it's exactly what i mean with this issue : use this library to generate sql like traditionnal MyBatis method and not encapsulate sql and parameter in the same bean. I was thinked that your library replace the "SQL" class of the MyBatis library, but it'is a more complete library with a different concept and use.

I understand your approach, and i understand that my approach is different of the goal of the library.

So I will think about it and decide if i continue with my own sql generator,replace it by yours or adapt yours to use with my approach.

Thank you for your attention

**Comment by jeffgbutler** [comment]
OK.  Thanks for your idea and the thoughtful discussion.

**Comment by jeffgbutler** [comment]
I don't know if this will work for you or not, but did you see that you can use the WHERE clause support on it;s own?  You can write the other parts of an SQL statement in a more traditional way with multiple parameters.  There's information about that here: http://www.mybatis.org/mybatis-dynamic-sql/docs/whereClauses.html#Stand_Alone_Where_Clauses

**Comment by tnicolas29200** [comment]
Hello,
Yes i have read that, it's very interresting and i'll use it for really dynamic sql queries. 

Don't worry about my need, i have developped some subclasses of your library to have the same comportement than the "SQL" class of MyBatis but with the power of your library for join or agregate functions.

Finally I successed to make select, update, delete and insert queries usable with a simple function call.
