### ISSUE TITLE
Most methods of mapper class generated by mybatis generator  are deprecated,what should I do?

### ISSUE THREAD

**Issue by 411937647** [mybatis/mybatis-dynamic-sql#151]
Mybatis generator version is 1.3.7,and mybatis-dynamic-sql version is 1.1.3.

Will  mybatis generator release an update recently？

I also noticed a project call "mybatis-generator2"  ，will this project be enabled instead of Mybatis generator recently?

**Comment by jeffgbutler** [comment]
I apologize for the confusion. I will explain this in the release notes for MyBatis Generator 1.4.0, but here's a quick preview...

MyBatis Generator 1.4.0 will, by default, generate code for the new version mybatis-dynamic-sql - and this will have a small impact on client code. The new style is much more consistent and flexible, so I hope that most users will quickly adopt it. This will be version 2 (V2) of the generators for mybatis-dynamic-sql.

MyBatis Generator 1.4.0 will still include the V1 generators for mybatis-dynamic-sql - but I will consider them deprecated and will remove them at some point.

This is fixed now in the MyBatis Generator master branch so you could use one of the snapshots to run the new generator if you want to try it before it gets "officially" released. You can look in the source code for MyBatis Generator and see the V1 and V2 generators if you are interested.

I am working on one more major enhancement for MyBatis Generator and then will release version 1.4.0. This should happen in the next couple of weeks.

mybatis-generator2 was an experiment I did a few years ago. What I came to understand is that the real problem was the generated code - not so much the generator itself (although that could certainly use some improvement). This is why I chose to build mybatis-dynamic-sql rather than spending time rewriting the generator. If you are interested, you can read more of my thoughts about that here: https://mybatis.org/mybatis-dynamic-sql/docs/motivation.html and here: https://github.com/mybatis/generator/issues/481

**Comment by 411937647** [comment]
Thank you for your answer.
I love the new mybatis-dynamic-sql, and the idea of using lambda instead of the chain method is great. Now I just have to focus on the where statement.
I run MyBatis Generator with JAVA like this,I hope I can help others with the same problem before the official release.
` Context context = new Context(null);
  context.setTargetRuntime("MyBatis3DynamicSqlV2");
`
I am looking forward to the release of MyBatis Generator 1.4.0.
Thank **jeffgbutler** again.
