### ISSUE TITLE
Feature request: add length/precision information to SqlColumn

### ISSUE THREAD

**Issue by djechelon** [mybatis/mybatis-dynamic-sql#388]
# Request

Change the SqlColumn class adding information about the column's length, precision and scale, using `Integer`s because obviously these are not defined for all columns.
The MyBatis Generator should populate every column accoding to information retrieved from the database during the generation process.

# Motivation

All our applications uses Flywaydb to manage migrations, so the DBA is not entitled to make random changes at column size.

Before inserting data, it is a nice requirement to early check the input parameters against maximum column length. At the current time, the developer needs to perform manual checks on input size by manually specifying the max length, e.g. (using Apache Commons lang3)

```
if (length(myColumn) > 25) throw new IllegalArgumentException();

```

It would be **nicer** to bind this check to information retrieved automatically from the database

```
public class MyClassSqlDynamicSupport {

    public static class MyClass extends SqlTable {

        public final SqlColumn<String> myColumn = column("MyColumn", JdbType.VARCHAR, 25);

    }

}


if (length(myColumn) > MyClassSqlDynamicSupport.mycolumn.length()) throw new IllegalArgumentException();


```

A similar approach can be done for `BigInteger`s and `NUMBER` columns, where calling code may check or **adjust** precision according to database instead of relying on SQLException to handle errors

**Comment by jeffgbutler** [comment]
I understand that does make some sense to think about this information as a part of `SqlColumn` because it is part of the database column description. But there is no need for that data in the library itself - it would only be used for some external purpose like validation. So I'm a bit hesitant to add it there.

Have you considered JSR-380 bean validation? It would be relatively simple to write a generator plugin that added those annotations to the generated model classes and I think the annotations on the model class would be more useful too.

**Comment by djechelon** [comment]
JSR-380 looks like a good compromise.

**Comment by jeffgbutler** [comment]
Thanks for your response.
