### ISSUE TITLE
Will it support query builder like this 

### ISSUE THREAD

**Issue by amazingman128** [mybatis/mybatis-dynamic-sql#464]
https://laravel.com/docs/9.x/queries

**Comment by jeffgbutler** [comment]
I don't understand your question. This library is a query builder. It relies on other frameworks to execute the SQL - either MyBatis or Spring JDBC.

**Comment by amazingman128** [comment]
sorry about that, I didn't express it in more detail.

For example I want to build a search query of table 'customer'
Now In mybatis-dynamic-sql  is like this 
`   fun search(id: String?, firstName: String?, lastName: String?) =
        select(Customer.id, Customer.firstName, Customer.lastName) {
            from(Customer)
            where { Customer.active.isTrue() }
            and { Customer.id (isEqualToWhenPresent(id).map{ it?.padStart(5, '0') }) }
            and { Customer.firstName (isLikeCaseInsensitiveWhenPresent(firstName)
                .map{ "%" + it.trim() + "%" }) }
            and { Customer.lastName (isLikeCaseInsensitiveWhenPresent(lastName)
                .map{ "%" + it.trim() + "%" }) }
            orderBy(Customer.lastName, Customer.firstName)
            limit(500)
        }`

In laravel it may like this  

`
DB::table('customer')
            ->select('id', 'first_name','last_name')
           ->where('active',true)
           ->orderBy('last_name', 'desc')
            ->limit(500)
`
i hope mybatis-dynamic-sql query builder can support  like it in laravel .  
For example from:  it can support  a tableName(String) : from("customer")

**Comment by jeffgbutler** [comment]
I don't know anything about Laravel, but from what I can tell there are two main differences:

1. This library must be used in combination with another framework that will execute the generated SQL. Currently we support MyBatis and Spring (as well as Java and Kotlin languages)
2. This library uses database model objects rather than accepting strings directly into the builders - this allows us to build type safe queries, and support multiple execution engines

The core MyBatis framework has some tools that will build SQL directly from string inputs (https://mybatis.org/mybatis-3/statement-builders.html). That method of query building is not type safe, but may be closer to what you are interested in.
