### ISSUE TITLE
Upgrade 1.2.1 to 1.4.1 and getting errors with `.or` 

### ISSUE THREAD

**Issue by mikebski** [mybatis/mybatis-dynamic-sql#557]
I upgraded from 1.2.1 to 1.4.1 and am getting an error on this statement:

```kotlin
val selectStatement =
                mapper.select { where(description, isLike("%${desc}%")).or(notes, isLike("%${desc}%")) }
```

The error is:

```
Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public inline infix fun BigInteger.or(other: BigInteger): BigInteger defined in kotlin
```

I've looked at the release notes and am not clear on what to do here. Can someone point me at the relevant documentation that will explain how to implement this properly? This is one of 4 similar errors in my test cases...

**Comment by jeffgbutler** [comment]
@mikebski the Kotlin where DSL has been completely rewritten since 1.2.1 - hopefully you will like it better!

This doc page explains how to use the updated Kotlin DSL, and how to migrate from prior releases: https://mybatis.org/mybatis-dynamic-sql/docs/kotlinWhereClauses.html

Specifically, for your example, the new form is like this:

```kotlin
val selectStatement = mapper.select {
  where {
    description isLike "%${desc}%"
    or { notes isLike "%${desc}%" }
  }
}
```

**Comment by mikebski** [comment]
Thanks for that link - this is working now and I do like it!
