### ISSUE TITLE
how can i auto generator id

### ISSUE THREAD

**Issue by pondered** [mybatis/mybatis-dynamic-sql#648]
<img width="976" src="https://github.com/mybatis/mybatis-dynamic-sql/assets/10516978/74438501-6bc3-4f6c-8722-926f0a5e75bf">

row is modify, but sql maybe use `insertStatementProvider.getInsertStatement()` use old , so i don't generator success
how can i generator ?

**Comment by jeffgbutler** [comment]
If you column mapping is like this: `...map(id).toProperty(id)`, then it should work.

However, if you are doing `...map(id).toPropertyWhenPresent(id, row::getId)`, then it won't work because the rendering happens before your interceptor is called.

**Comment by pondered** [comment]
i use interceptor generator not manually

**Comment by jeffgbutler** [comment]
I don't know what that means. Do you have a small sample project you can share?

**Comment by pondered** [comment]
and invocation.getArgs[1] type instance is DefaultInsertStatementProvider?

**Comment by pondered** [comment]
> <img width="976" src="https://github.com/mybatis/mybatis-dynamic-sql/assets/10516978/74438501-6bc3-4f6c-8722-926f0a5e75bf">
> 
> 
> 
> row is modify, but sql maybe use `insertStatementProvider.getInsertStatement()` use old , so i don't generator success
> 
> how can i generator ?



this image

**Comment by pondered** [comment]
> I don't know what that means. Do you have a small sample project you can share?


sorry，I'm not with my computer

**Comment by jeffgbutler** [comment]
I can only guess what you mean. If you are referring to the code created by MyBatis Generator, then your interceptor should work with the generated `insert` method, but may not work with the `insertSelective` method.

If that's not it, then please create a [SSCCE](http://sscce.org/) that demonstrates the issue you are having and share it on GitHub. Images of code are not helpful in general.

**Comment by pondered** [comment]
no， not mybatis generator,is runtime generator pk in db

**Comment by pondered** [comment]
like this [](https://github.com/lyb-geek/springboot-learning/blob/master/springboot-mybatis-autoId/src/main/java/com/github/lybgeek/autoid/interceptor/AutoIdInterceptor.java)

**Comment by jeffgbutler** [comment]
I'm not clear if you are using this library or not. I think you are saying that you are not using this library, but the parameters in the interceptor suggest you are. Maybe there is a mix of SQL generated by this library, and other manual SQL?

If you are using this library, then it would be best to set the ID in the record object rather than using this interceptor. In any case, the interceptor might need to parse and rewrite SQL which seems difficult and full of potential corner cases.

The interceptor you reference is not part of our project and not supported by us. If you have issues using it, I suggest you reach out to the authors of that project for help.
