### ISSUE TITLE
How to remove `@ConstructorArgs` ?

### ISSUE THREAD

**Issue by pondered** [mybatis/mybatis-dynamic-sql#652]
i use `mapper.selectOne` method, but just select single column.  
eg: `mapper.selectOne(select(type)...)` throw  

<img width="1392" src="https://github.com/mybatis/mybatis-dynamic-sql/assets/10516978/d454d688-51a6-49ca-9dac-00109dfc6cd3">

because `selectOne` method use 
<img width="782" alt="mapper" src="https://github.com/mybatis/mybatis-dynamic-sql/assets/10516978/440eb972-686c-4627-bc22-aeb51a67cb20">

so i think remove `ConstrauctorAgs` or other modalities ?

**Comment by jeffgbutler** [comment]
In MyBatis, the result mapping must match the query. You can remove the constructor arg here if, and only if, you're not using this mapper in other places.

We supply a generic mapper that can be used for any query - `org.mybatis.dynamic.sql.util.mybatis3.CommonSelectMapper`. The `selectOneInteger` method in that mapper would work well in this situation.

**Comment by pondered** [comment]
oh ,thanks ,but i see mapper not extends CommonSelectMapper, why?

**Comment by jeffgbutler** [comment]
MyBatis Generator does not generate mappers that extend the CommonSelectMapper because the generator builds result maps that match the table rows.

You can can make the change to have your mapper extend CommonSelectMapper along with the other common mappers, or you could just add the CommonSelectMapper standalone to your configuration, or you could write a generator plugin to add this extension to every mapper or a subset of mappers. Whatever makes the most sense in your usage model will work. If it were me, I would just add the CommonSelectMapper to your configuration one time.
