### ISSUE TITLE
Add support for sql-server top x syntax

### ISSUE THREAD

**Issue by FrancisS** [mybatis/mybatis-dynamic-sql#658]
There appears to be no support for SQL Server "SELECT TOP x" syntax.  Support for MySql "LIMIT x" and oracle "FETCH FIRST x ROWS ONLY" does exist. Unless I am missing something it would be nice to add support for SQL server syntax.

**Comment by jeffgbutler** [comment]
Limit and fetch first are supported. See these tests for examples:

https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/animal/data/LimitAndOffsetTest.java
https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/animal/data/FetchFirstTest.java

**Comment by jeffgbutler** [comment]
Ah...

It's been a long time since I did anything with SQL Server so I'm not familiar with TOP. From the docs, it looks like something you could do with a function you could write - see this as an example: https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/main/java/org/mybatis/dynamic/sql/select/function/Lower.java

If you want the values of TOP to be passed as prepared statement parameters, then you'll need to wait until there is a fix for #655 - which should come soon.

**Comment by FrancisS** [comment]
I followed that pattern and this seems to work. However its only valid to use with the first column in the select list so its a little bit awkward.
```
public class Top<T> extends AbstractUniTypeFunction<T, Top<T>> {
    private final int number;

    private Top(BindableColumn<T> column, int number) {
        super(column);
        this.number = number;
    }

    @Override
    public String renderWithTableAlias(TableAliasCalculator tableAliasCalculator) {
        return String.format("TOP %s ", number) + column.renderWithTableAlias(tableAliasCalculator);
    }

    @Override
    protected Top<T> copy() {
        return new Top<>(column, number);
    }
    public static <T> Top<T> of(BindableColumn<T> column, int number) {
        return new Top<>(column, number);
    }

}
```

**Comment by jeffgbutler** [comment]
Glad to know it worked. I'm not sure what you mean about it being awkward - is that because of something in this library, or because of a SQL Server restriction?

**Comment by FrancisS** [comment]
Only because its possible to use the function in a way that will produce invalid SQL. Its syntactically possible to use it with any column but its only semantically valid if used for the first one in the list.

**Comment by jeffgbutler** [comment]
That makes sense. Not sure there's anything we can do about that. I suppose you could create a little convenience method that would make it a bit more clear:

```java
static QueryExpressionDSL.FromGatherer<SelectModel> select(Top<?> top,
        BindableColumn<?>...bindableColumns) {
    List<BindableColumn<?>> list = new ArrayList<>();
    list.add(top);
    list.addAll(Arrays.asList(bindableColumns));

    return SqlBuilder.select(list);
}
```

**Comment by katnova** [comment]
As far as I can tell, this feature is still not present in `org.mybatis.dynamic.sql.util.kotlin.KotlinSelectBuilder` or `org.mybatis.dynamic.sql.select.SelectDSL`.

Wondering if it's possible to get this still, since it's just `SELECT TOP(x) <COLS> ...`. and MySQL's `limit` and Oracle's `fetchFirst` are present.

Example:
```kotlin
// Equivilent to: SELECT TOP(?) someidcol, timestampcolumn FROM Cooltable WHERE someidcol = ? ORDER BY timestampcolumn DESC
cooltableMapper.select { //<-- SelectCompleter / KotlinSelectBuilder
     top(10L) //<-- Being able to do this here would be super cool.
     where { 
          CooltableDynamicSqlSupport.someidcol isEqualTo someidcol 
     }
     orderBy(CooltableDynamicSqlSupport.timestampcolumn.descending())
}
```
